---
- name: Create Jenkins user
  ansible.builtin.user:
    name: "{{ jenkins_process_user }}"
    shell: /bin/bash

- name: Create Jenkins installation directory
  ansible.builtin.file:
    path: "{{ jenkins_install_dir }}"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: "0755"

- name: Download Jenkins WAR file
  ansible.builtin.get_url:
    url: "{{ jenkins_url }}"
    dest: "{{ jenkins_install_dir }}/jenkins.war"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: '0644'
  notify: Configure default users

- name: Create systemd service file for Jenkins
  ansible.builtin.template:
    src: jenkins.service.j2
    dest: "/etc/systemd/system/jenkins.service"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: "0664"
  notify:
    - Restart jenkins

- name: Ensure Jenkins directory ownership
  ansible.builtin.file:
    path: "{{ jenkins_install_dir }}/jenkins_home"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: "0755"
