---
- name: Initialize Jenkins Variables
  ansible.builtin.include_tasks: facts.yml

- name: Install Jenkins Server
  ansible.builtin.include_tasks: install.yml

- name: Configure Jenkins Server Settings
  ansible.builtin.include_tasks: settings.yml

- name: Execute Post-Installation Tasks
  ansible.builtin.include_tasks: post.yml

- name: Install and Configure Jenkins Plugins
  ansible.builtin.include_tasks: plugins.yml
