---
- name: Install
  hosts: all

  vars:
    jenkins_plugins:
      - greenballs
      - {name: cloudbees-folder, version: 6.795.v3e23d3c6f194}
    jenkins_home: /var/lib/jenkins
    jenkins_plugin_timeout: 120

  roles:
    - role: exzeo.java
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  post_tasks:
    - name: Verify JENKINS_HOME is correct.
      ansible.builtin.stat:
        path: "{{ jenkins_home }}/config.xml"
      register: jenkins_home_config

    - name: Fail if Jenkins config file doesn't exist.
      ansible.builtin.fail:
      when: not jenkins_home_config.stat.exists

    - name: List plugins directory contents.
      ansible.builtin.command: "ls {{ jenkins_home }}/plugins"
      register: plugins_contents
      changed_when: false
      tags: ["skip_ansible_lint"]

    - name: Verify greenballs plugin exists.
      ansible.builtin.stat:
        path: "{{ jenkins_home }}/plugins/greenballs.jpi"
      register: greenballs_plugin

    - name: Fail if greenballs plugin file doesn't exist.
      ansible.builtin.fail:
      when: not greenballs_plugin.stat.exists

    - name: Verify cloudbees-folder plugin exists.
      ansible.builtin.stat:
        path: "{{ jenkins_home }}/plugins/cloudbees-folder.jpi"
      register: folder_plugin

    - name: Fail if cloudbees-folder plugin file doesn't exist.
      ansible.builtin.fail:
      when: not folder_plugin.stat.exists

    - name: Ensure Jenkins is running.
      ansible.builtin.uri:
        url: "http://127.0.0.1:8080/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
