---
- name: Install
  hosts: all

  vars:
    jenkins_url_prefix: /jenkins

  roles:
    - role: exzeo.java
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  post_tasks:
    - name: Ensure Jenkins is running with the specified prefix
      ansible.builtin.uri:
        url: "http://127.0.0.1:8080{{ jenkins_url_prefix }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
